### ISSUE TITLE
Locale not found

### ISSUE THREAD

**Issue by CalvinScott** [nodeca/charlatan#13]
For some reason I keep getting this error when installing the newest version.

/pipeline/build/node_modules/charlatan/lib/charlatan.js:86
      throw new Error('Locale not found:' + name);
            ^
Error: Locale not found:en-us
    at exports.addLocale (/pipeline/build/node_modules/charlatan/lib/charlatan.js:86:13)
    at Object.exports.setLocale (/pipeline/build/node_modules/charlatan/lib/charlatan.js:131:5)

**Comment by puzrin** [comment]
try `en-US`, not `en-us`.

**Comment by puzrin** [comment]
Closing - not a bug, wrong locale name in params.
